# Generated by Django 3.2.4 on 2021-06-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_auto_20210619_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Placesfor',
            new_name='Team',
        ),
    ]
